## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])

def multiply_two_vector(v,w):

    assert len(v)==len(w), "the length must be equal"  # To make sure the length is equal
    return [a_i*b_i for a_i,b_i in zip(v,w)]

def multiply_two_matrix(a,b):
    c=[]
    for i in range(len(a)):
          c.append(multiply_two_vector(a[i],b[i]))
    return c
multiply_two_matrix(a,b)
# The output will be the product of each value being multiplied by its corresponding value

[[1, 4, 9], [16, 25, 36]]

In [3]:
# other solution 
my_array1=np.array([[1,2,3],[1,2,3]])
my_array2=np.array([[1,2,3],[1,2,3]])
print(my_array1*my_array2)

[[1 4 9]
 [1 4 9]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
my_array=np.array([[1,2],[3,4]])
det_of_matrix=np.linalg.det(my_array,)
print(det_of_matrix)

-2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [6]:
a=[1,2,3]
b=[4,5,6]
cross_prod=np.cross(a,b)
print(cross_prod)

[-3  6 -3]


## Write a NumPy program to compute the condition number of a given matrix

In [7]:
a=np.array([[1,2,3],[4,5,6]])
con_number=np.linalg.cond(a)
print(f"the condition number is {con_number}")


the condition number is 12.302245504069202


## Write a NumPy program to compute the inverse of a given matrix

In [9]:
a=np.array([[1,2],[4,5]])
inv_of_matrix=np.linalg.inv(a)
print(f"the inverse of matrix is {inv_of_matrix}")

the inverse of matrix is [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
